### ISSUE TITLE
Support for discord webhook

### ISSUE THREAD

**Issue by alessandrocaprarelli** [valeriansaliou/vigil#44]
Hi,

it would be awesome to have a notifier for discord.

Regards,
Alessandro

**Comment by Rhydium** [comment]
@valeriansaliou why did you remove this from the v2.0.0 milestone?

**Comment by valeriansaliou** [comment]
I don’t plan on supporting Discord in the core.

**Comment by mayone** [comment]
You can use Discord's [Slack-Compatible Webhook](https://discord.com/developers/docs/resources/webhook#execute-githubcompatible-webhook)
Which will look like this
```toml
[notify.slack]

hook_url = "DISCORD_WEBHOOK_URL/slack"
mention_channel = true
```
