### ISSUE TITLE
Correct way to check SMTP IMAP Servers

### ISSUE THREAD

**Issue by Ciangi** [valeriansaliou/vigil#84]
Hi,

i have configuration like this:

```
[[probe.service.node]]

id = "smtp-server"
label = "SMTP Service"
mode = "poll"

replicas = [
  "tcp://192.168.100.205:25"
]
```

but i got errors in logs:
```
prober poll error for tcp target: 192.168.100.205:25 (error: Connection refused (os error 111))
```

But im 100% sure that smtp is working because im using it and sending mails works etc..

What is a problem?

Greetings

**Comment by valeriansaliou** [comment]
Does `telnet 192.168.100.205 25` works on the machine running Vigil? I'm pretty sure there's a firewall involved somewhere.

**Comment by Ciangi** [comment]
![obraz](https://user-images.githubusercontent.com/15123509/114875719-df164f00-9dfd-11eb-88ab-a3a51e6ed464.png)

telnet works like a charm

**Comment by Ciangi** [comment]
Hmm btw i testing telnet from Docker HOST...

i created vigil container like:

```
version: "3"
services:
    vigil:
        image: valeriansaliou/vigil:v1.21.1
        volumes:
          - ./config.cfg:/etc/vigil.cfg
          - /etc/localtime:/etc/localtime:ro 
        networks:
          myvlan:
            ipv4_address: 192.168.100.15
networks:
  myvlan:
    external:
      name: mynet
```


and i noticed that problem after some days. Like 2 days running everything was working, just today noticed that problem but mail server still running..
